### PR TITLE
Redid the entire channel/profile page.

### PR DESCRIPTION
**Pull request by paulr093**
Eliminated redux from the page redid the sidebar. Updated a lot of components to mantine. All functionality should be the same. Things to review: 

- [x] Got rid of forced fallback page - make sure the rest of site works properly
- [x] Placement of ad under sidebar scroller
- [x] ?k=kitName should work completely normal - to accommodate for customTitle's i added that to the query and the functionality was added to find the correct kit.

### CODE REVIEW

**Comment by anthonyshew** [comment]
This gap is too big.

image

**Comment by anthonyshew** [comment]
It's weird to see `Kastov 762` in the nested button, too. What makes sense instead..."Default?"

image

**Comment by anthonyshew** [comment]
`another` needs a star when in the dropdown list.

image

**Comment by anthonyshew** [comment]
Need to filter out empty categories.

image

**Comment by anthonyshew** [comment]
I moved to mobile size and the empty space at the bottom got taller. We won't block the ship with this but just a mental note to check it.

image

**Comment by anthonyshew** [comment]
This "weight" is too far from the name of the attachment (white text). Can it get closer?

image

**Comment by paulr093** [comment]
- [ ] left side gap on sidebar button text is too big
- [ ] show default kit in a drop down menu instead of kit name
- [ ] show featured star in drop down menu
- [ ] filter out empty category names
- [ ] get rid of ad space
- [ ] tunes are too far apart in container

**Comment by anthonyshew** [comment]
image

I'm getting this in dev mode.

My sidebar is also showing up with a white background (probably related).

**Comment by anthonyshew** [comment]
image


I've got background of sidebar showing up as white and funky padding/margin between the sidebar and body.

**Pull request merged**
